//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoyalIGWEB.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Loyal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loyal() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoyalIGWEB.Resources.Loyal", typeof(Loyal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accese a su cuenta.
        /// </summary>
        internal static string AcceseCuenta {
            get {
                return ResourceManager.GetString("AcceseCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aesgurados.
        /// </summary>
        internal static string Aesgurados {
            get {
                return ResourceManager.GetString("Aesgurados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agentes.
        /// </summary>
        internal static string Agentes {
            get {
                return ResourceManager.GetString("Agentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Años.
        /// </summary>
        internal static string Años {
            get {
                return ResourceManager.GetString("Años", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Aqui ....
        /// </summary>
        internal static string BuscarAqui {
            get {
                return ResourceManager.GetString("BuscarAqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comisiones.
        /// </summary>
        internal static string Comisiones {
            get {
                return ResourceManager.GetString("Comisiones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Complicaciones de Maternidad.
        /// </summary>
        internal static string ComplicacionesMaternidad {
            get {
                return ResourceManager.GetString("ComplicacionesMaternidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Contraseña {
            get {
                return ResourceManager.GetString("Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conyuge.
        /// </summary>
        internal static string Conyuge {
            get {
                return ResourceManager.GetString("Conyuge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        internal static string Correo {
            get {
                return ResourceManager.GetString("Correo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo Administrativo.
        /// </summary>
        internal static string CostoAdministrativo {
            get {
                return ResourceManager.GetString("CostoAdministrativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotización.
        /// </summary>
        internal static string Cotizacion {
            get {
                return ResourceManager.GetString("Cotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cotizar.
        /// </summary>
        internal static string Cotizar {
            get {
                return ResourceManager.GetString("Cotizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dashboard.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Demografico.
        /// </summary>
        internal static string Demografico {
            get {
                return ResourceManager.GetString("Demografico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependiente.
        /// </summary>
        internal static string Dependiente {
            get {
                return ResourceManager.GetString("Dependiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dependientes.
        /// </summary>
        internal static string Dependientes {
            get {
                return ResourceManager.GetString("Dependientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string Espanol {
            get {
                return ResourceManager.GetString("Espanol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimiento.
        /// </summary>
        internal static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Femenino.
        /// </summary>
        internal static string Femenino {
            get {
                return ResourceManager.GetString("Femenino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar Cotización.
        /// </summary>
        internal static string GenerarCotizacion {
            get {
                return ResourceManager.GetString("GenerarCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Igresos / Egresos.
        /// </summary>
        internal static string IgresosEgresos {
            get {
                return ResourceManager.GetString("IgresosEgresos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de Cotización.
        /// </summary>
        internal static string InformacionCotizacion {
            get {
                return ResourceManager.GetString("InformacionCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Solicitante.
        /// </summary>
        internal static string InformacionSolicitante {
            get {
                return ResourceManager.GetString("InformacionSolicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        internal static string Ingles {
            get {
                return ResourceManager.GetString("Ingles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de Validez.
        /// </summary>
        internal static string InicioValidez {
            get {
                return ResourceManager.GetString("InicioValidez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar Cotización.
        /// </summary>
        internal static string LimpiarCotizacion {
            get {
                return ResourceManager.GetString("LimpiarCotizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Masculino.
        /// </summary>
        internal static string Masculino {
            get {
                return ResourceManager.GetString("Masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tienes cuenta?.
        /// </summary>
        internal static string NoTienesCuenta {
            get {
                return ResourceManager.GetString("NoTienesCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Olvido su contraseña?.
        /// </summary>
        internal static string OlvidoContraseña {
            get {
                return ResourceManager.GetString("OlvidoContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas.
        /// </summary>
        internal static string Personas {
            get {
                return ResourceManager.GetString("Personas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Portugués.
        /// </summary>
        internal static string Portugues {
            get {
                return ResourceManager.GetString("Portugues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primas Cobradas.
        /// </summary>
        internal static string PrimasCobradas {
            get {
                return ResourceManager.GetString("PrimasCobradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Principal.
        /// </summary>
        internal static string Principal {
            get {
                return ResourceManager.GetString("Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuérdame.
        /// </summary>
        internal static string Recuerdame {
            get {
                return ResourceManager.GetString("Recuerdame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrate.
        /// </summary>
        internal static string Registrate {
            get {
                return ResourceManager.GetString("Registrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renovación.
        /// </summary>
        internal static string Renovacion {
            get {
                return ResourceManager.GetString("Renovacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Agente.
        /// </summary>
        internal static string SeleccioneAgente {
            get {
                return ResourceManager.GetString("SeleccioneAgente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione número dependientes.
        /// </summary>
        internal static string SeleccioneDependientes {
            get {
                return ResourceManager.GetString("SeleccioneDependientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione Genero.
        /// </summary>
        internal static string SeleccioneGenero {
            get {
                return ResourceManager.GetString("SeleccioneGenero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SeleccionePais.
        /// </summary>
        internal static string SeleccionePais {
            get {
                return ResourceManager.GetString("SeleccionePais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TextoComparado.
        /// </summary>
        internal static string TextoComparado {
            get {
                return ResourceManager.GetString("TextoComparado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titular.
        /// </summary>
        internal static string Titular {
            get {
                return ResourceManager.GetString("Titular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total de Primas.
        /// </summary>
        internal static string TotaldePrimas {
            get {
                return ResourceManager.GetString("TotaldePrimas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trasplantes de Organos.
        /// </summary>
        internal static string TrasplantesOrganos {
            get {
                return ResourceManager.GetString("TrasplantesOrganos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Venta Nueva.
        /// </summary>
        internal static string VentaNueva {
            get {
                return ResourceManager.GetString("VentaNueva", resourceCulture);
            }
        }
    }
}
